# Generated by Django 2.2.7 on 2019-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
